### ISSUE TITLE
Wrong movie gets expanded when you select your top 3 movies while you have an unrated movie

### ISSUE THREAD

**Issue by MainHobo** [Team-LAMA/watchlist_app#37]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by seedback** [comment]
fixed in commit 7c916508867bfd81afd3baceff00d641f8ec9905
