### ISSUE TITLE
css bug for sign in when the wrong messasge comes up the input moves

### ISSUE THREAD

**Issue by Linnova98** [Team-LAMA/watchlist_app#44]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by seedback** [comment]
fixed in commit f65c85f8c1b2ee42c3f30f3ce3bb7c8919b5e78b
